### ISSUE TITLE
Bug - The light theme is broken in the tutorial overview page

### ISSUE THREAD

**Issue by sofiaromorales** [apple/swift-docc-render#240] opened 2022-04-29 20:55 UTC
**Describe the bug**

On the main tutorials page, the light theme is not being applied to the entire page, just to the footer.

**Expected behavior**

When clicking on `Light` in the `color-scheme-toggle` the light theme should be applied to the entire page transforming the dark colors into the white-themed colors

**Actual behavior**

When clicking on `Light` in the `color-scheme-toggle` the light theme is only applied to the footer.

**Steps to reproduce**

1. Open http://localhost:8080/tutorials/slothcreator in Safari (or any web browser)
2. Select `Light` at the color scheme preference selector

**Environment**

Safari 15.3
Testing locally using `swift-docc-render` repo with HEAD in commit id [3425d37](https://github.com/apple/swift-docc-render/commit/3425d376aee730ca74125263f4bf52e942c1a3cf) and the `SlothCreator.doccarchive` file

**Possible solution**

In some of the components, the background and color properties are set directly to use the dark theme, instead of using the CSS variable that is dynamically applied when the `data-color-scheme` changes. The `dark-color(color-name)` values should be changed to `var(--css-color-name)`

```js
// src/components/TutorialsOverview/LearningPath.vue
.learning-path {
  background: dark-color(fill);
  ...
}
```

```js
// src/components/TutorialsOverview/ResourcesTile.vue
.tile {
 background: dark-color(fill-secondary);
  ...
}
```

```js
// src/components/TutorialsOverview/TutorialsNavigationMenu.vue
$inactiveColor: dark-color(figure-gray-secondary-alt);
$hoverColor: dark-color(figure-gray-secondary-alt);
```

```js
// src/components/TutorialsOverview/Volume.vue
.tile {
  background: dark-color(fill-secondary);
  ...
}
```

Also in the `_light.scss` file some of the CSS variables inside the mixin `color-vars-light` use the dark version of the Sass color
```js
// src/styles/core/colors/_light.scss
--color-tutorials-overview-background: #{dark-color(fill-secondary)};
--color-tutorials-overview-content: #{dark-color(figure-gray)};
--color-tutorials-overview-content-alt: #{dark-color(figure-gray)};
--color-tutorials-overview-eyebrow: #{dark-color(figure-gray-secondary)};
```

**Attachment**

<img width="1440" alt="Screen Shot 2022-04-29 at 4 12 35 PM" src="https://user-images.githubusercontent.com/49292858/166065102-9b72c9b0-46df-4909-b3f6-74476f88369f.png">

**Comment by sofiaromorales** [comment] 2022-04-29 20:57
I would like to take care of this one 🙋‍♀️

**Comment by marinaaisa** [comment] 2022-05-02 18:03
Hi @sofiaromorales !
Your reasoning makes total sense but there is some design context missing out:
This page does not have a light mode version, because it is a Dark Theme page. This means that by design, it has a dark theme in light mode and in dark mode. Our design system provides affordances for when we visually want something to be dark as a contrasting element/page to our light theme pages. The main purpose of dark mode is to provide an equally comfortable and functional experience using the interface in a dimly lit environment, which means that we invert all of our light theme content for dark mode but we don't invert our dark theme content to light theme for dark mode pages.

I hope this clarify the issue. I'm going to close it but thank you so much for opening it and bring this topic up! It shows your strong attention on this project's UI details.

**Closed by marinaaisa** 2022-05-02 18:03 UTC
